# -*- coding: utf-8 -*-
"""LXI-assisted tests for TCPIP resources.

This package is meant to run against fake instruments started by the
dedicated pyvisa-tester harness.

To enable this part of the testsuite, set PYVISA_LXI_ASSISTED.
In CI, use the prebuilt `pyvisa-lxi-fake` binary from pyvisa-tester releases.

Optional environment variables:
- PYVISA_LXI_ENV_FILE: path to KEY=VALUE file generated by the harness
- PYVISA_LXI_VXI11=0: disable VXI-11 tests
- PYVISA_LXI_VXI11_ADDR:  VXI-11 resource address
- PYVISA_LXI_HISLIP_ADDR: HiSLIP resource address
- PYVISA_LXI_SOCKET_ADDR: Raw socket resource address
- PYVISA_LXI_HISLIP=0: disable HiSLIP tests
- PYVISA_LXI_SOCKET=0: disable raw socket tests
- PYVISA_LXI_EXPECTED_IDN: expected *IDN? response
"""

import functools
import os
import types

import pytest

from .env_helpers import load_lxi_env_from_file

load_lxi_env_from_file()

_LXI_AVAILABLE = "PYVISA_LXI_ASSISTED" in os.environ
_VXI11_AVAILABLE = _LXI_AVAILABLE and os.environ.get("PYVISA_LXI_VXI11", "1") != "0"
_HISLIP_AVAILABLE = _LXI_AVAILABLE and os.environ.get("PYVISA_LXI_HISLIP", "1") != "0"
_SOCKET_AVAILABLE = _LXI_AVAILABLE and os.environ.get("PYVISA_LXI_SOCKET", "1") != "0"

require_lxi_assisted = pytest.mark.skipif(
    not _LXI_AVAILABLE,
    reason="Requires the LXI fake instruments. Set PYVISA_LXI_ASSISTED.",
)

require_lxi_vxi11 = pytest.mark.skipif(
    not _VXI11_AVAILABLE,
    reason="Requires VXI-11 endpoint. Set PYVISA_LXI_VXI11_ADDR or PYVISA_LXI_VXI11=1.",
)

require_lxi_hislip = pytest.mark.skipif(
    not _HISLIP_AVAILABLE,
    reason="Requires HiSLIP endpoint. Set PYVISA_LXI_HISLIP_ADDR or PYVISA_LXI_HISLIP=1.",
)

require_lxi_socket = pytest.mark.skipif(
    not _SOCKET_AVAILABLE,
    reason="Requires raw socket endpoint. Set PYVISA_LXI_SOCKET_ADDR or PYVISA_LXI_SOCKET=1.",
)

RESOURCE_ADDRESSES = {
    "TCPIP::INSTR": os.environ.get(
        "PYVISA_LXI_VXI11_ADDR", "TCPIP::127.0.0.1::inst0::INSTR"
    ),
    "TCPIP::HISLIP": os.environ.get(
        "PYVISA_LXI_HISLIP_ADDR", "TCPIP::127.0.0.1::hislip0::INSTR"
    ),
    "TCPIP::SOCKET": os.environ.get(
        "PYVISA_LXI_SOCKET_ADDR", "TCPIP::127.0.0.1::5025::SOCKET"
    ),
}

EXPECTED_IDN = os.environ.get(
    "PYVISA_LXI_EXPECTED_IDN", "Cyberdyne systems,T800 Model 101,A9012.C,V2.4"
)


# Even a deepcopy is not a true copy of a function.
def copy_func(f):
    """Based on http://stackoverflow.com/a/6528148/190597 (Glenn Maynard)."""
    g = types.FunctionType(
        f.__code__,
        f.__globals__,
        name=f.__name__,
        argdefs=f.__defaults__,
        closure=f.__closure__,
    )
    g = functools.update_wrapper(g, f)
    kwdefaults = getattr(f, "__kwdefaults__", None)
    if kwdefaults is not None:
        setattr(g, "__kwdefaults__", kwdefaults)
    return g
